Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.hostname = "client.local"
  config.vm.network "private_network", ip: "192.168.56.11"

  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.name = "ClientVM"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y curl nmap
  SHELL
end

