Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  
  config.vm.hostname = "server.local"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.name = "ServerVM"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nginx ufw
    echo '<h1>Bienvenue sur le serveur Nginx</h1>' | sudo tee /var/www/html/index.html
    sudo systemctl start nginx
    sudo systemctl enable nginx
    sudo ufw allow 80,443,22/tcp
    sudo ufw enable
  SHELL
end

